# Task ID     : 97d77abe
# Tasks       : 5/5 passed
# Requirement : 用 Python 实现一个栈（Stack）数据结构，要求支持 push、pop、peek、is_empty 方法，包含类型注解和错误处理
# Generated by: Design-Code Multi-Agent System (LangGraph)


# ════════════════════════════════════════════════════════════
# Subtask: 定义栈类  [✓ passed]
# ════════════════════════════════════════════════════════════
class Stack:
    def __init__(self) -> None:
        # 初始化一个空列表，用于存储栈元素，使用类型注解确保类型安全
        self.items: list = []


# ════════════════════════════════════════════════════════════
# Subtask: 实现 push 方法  [✓ passed]
# ════════════════════════════════════════════════════════════
from typing import Any

class Stack:
    def __init__(self):
        # 初始化一个空列表来存储栈中的元素
        self.items = []

    def push(self, item: Any) -> None:
        """
        将元素 item 添加到栈顶。

        参数:
        item (Any): 要添加到栈顶的元素。
        """
        # 使用列表的 append 方法将元素添加到列表末尾，即栈顶
        self.items.append(item)


# ════════════════════════════════════════════════════════════
# Subtask: 实现 pop 方法  [✓ passed]
# ════════════════════════════════════════════════════════════
from typing import Any

class Stack:
    def __init__(self):
        # 初始化一个空列表来存储栈元素
        self.items = []

    def pop(self) -> Any:
        """
        移除并返回栈顶元素。

        如果栈为空，抛出 IndexError 异常。

        Returns:
            Any: 栈顶元素。
        """
        # 检查栈是否为空
        if len(self.items) == 0:
            # 若为空，抛出 IndexError 异常
            raise IndexError("栈为空")
        # 若不为空，使用列表的 pop 方法移除并返回栈顶元素
        return self.items.pop()


# ════════════════════════════════════════════════════════════
# Subtask: 实现 peek 方法  [✓ passed]
# ════════════════════════════════════════════════════════════
from typing import Any

class Stack:
    def __init__(self):
        # 初始化一个空列表来存储栈中的元素
        self.items = []

    def peek(self) -> Any:
        """
        返回栈顶元素，但不移除它。

        如果栈为空，抛出 IndexError 异常。

        Returns:
            Any: 栈顶元素。
        """
        # 检查栈是否为空
        if len(self.items) == 0:
            # 若栈为空，抛出 IndexError 异常
            raise IndexError("peek from empty stack")
        # 若栈不为空，返回栈顶元素
        return self.items[-1]


# ════════════════════════════════════════════════════════════
# Subtask: 实现 is_empty 方法  [✓ passed]
# ════════════════════════════════════════════════════════════
class Stack:
    def __init__(self):
        # 初始化一个空列表作为栈的底层存储结构
        self.items = []

    def is_empty(self) -> bool:
        """
        判断栈是否为空。

        返回值:
            bool: 如果栈为空返回 True，否则返回 False。
        """
        # 通过检查列表长度是否为 0 来判断栈是否为空
        return len(self.items) == 0