# Task ID     : d0f71f10
# Tasks       : 3/3 passed
# Requirement : 用 Python 实现二分查找算法，要求有类型注解、完善的错误处理，并通过如下测试：binary_search([1,3,5,7,9], 7) == 3，binary_search([1,3,5,7,9], 10) == -1
# Generated by: Design-Code Multi-Agent System

# ════════════════════════════════════════════════════════════
# Subtask: 定义函数和参数类型  [✓ passed]
# ════════════════════════════════════════════════════════════
def binary_search(arr: list[int], target: int) -> int:
    """    该函数接收一个有序整数列表和一个整数目标值，返回目标值在列表中的索引，如果未找到则返回 -1    :param arr: 有序整数列表    :param target: 要查找的整数目标值    :return: 目标值在列表中的索引，如果未找到则返回 -1    """
    pass


# ════════════════════════════════════════════════════════════
# Subtask: 实现二分查找逻辑  [✓ passed]
# ════════════════════════════════════════════════════════════
def binary_search(arr: list[int], target: int) -> int:
    """在有序列表 arr 中查找目标元素 target，若找到返回其索引，未找到返回 -1。

    Args:
        arr (list[int]): 有序整数列表。
        target (int): 要查找的目标整数。

    Returns:
        int: 目标元素的索引，如果未找到则返回 -1。
    """
    # 处理列表为空的边缘情况
    if not arr:
        return -1
    # 步骤 1: 初始化左右边界指针
    left, right = 0, len(arr) - 1
    # 步骤 2: 进入循环，条件为 left 小于等于 right
    while left <= right:
        # 步骤 3: 在循环内部，计算中间位置 mid
        mid = (left + right) // 2
        # 步骤 4: 判断中间位置的元素是否等于目标元素
        if arr[mid] == target:
            return mid
        # 步骤 5: 如果中间位置的元素大于目标元素，更新 right 为 mid - 1
        elif arr[mid] > target:
            right = mid - 1
        # 步骤 6: 如果中间位置的元素小于目标元素，更新 left 为 mid + 1
        else:
            left = mid + 1
    # 步骤 7: 若循环结束仍未找到目标元素，返回 -1
    return -1


# ════════════════════════════════════════════════════════════
# Subtask: 添加错误处理  [✓ passed]
# ════════════════════════════════════════════════════════════
def binary_search(arr: list[int], target: int) -> int:
    # 步骤 1: 检查输入列表是否为空，如果为空，直接返回 -1
    if not arr:
        return -1
    # 步骤 2: 遍历列表，检查列表是否有序
    for i in range(len(arr) - 1):
        if arr[i] > arr[i + 1]:
            raise ValueError("列表必须有序")
    # 步骤 3: 若列表有序且不为空，执行原有的二分查找逻辑
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == target:
            return mid
        elif arr[mid] < target:
            left = mid + 1
        else:
            right = mid - 1
    # 步骤 4: 如果未找到目标值，返回 -1
    return -1